# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OmniBot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


 target 'OmniBotTests' do
    inherit! :search_paths
    # Pods for testing
 end

 target 'OmniBotUITests' do
    inherit! :search_paths
    # Pods for testing
 end

end

 # Pods for OmniBot
pod 'BRHJoyStickView'
pod 'CocoaLumberjack/Swift'
